name: Check Test Cases

on:
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  test:  
    name: Check Test Cases  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Give gradlew permission to execute
        run: chmod +x ./gradlew

      - name: Run tests and enforce 80% coverage
        run: ./gradlew clean test jacocoTestReport jacocoTestCoverageVerification
